version: '3'

services:
  frontend:
    build: ./frontend/
    ports:
      - "8081:8080"
    depends_on:
      - "backend"
    links:
      - backend

  backend:
    build: ./backend/
    ports:
      - "5000:8080"
    depends_on:
      - "mongo"
  mongo:
    image: mongo
    ports:
      - 27017:27017
